#!/usr/bin/env sh

# Stop commit if the build fails
npm run build || exit 1

echo "citynaturechoices.org" > docs/CNAME

cp terms.html docs/terms.html

# If build succeeds, include docs/ in the commit
git add docs
git add docs/terms.html

